### ISSUE TITLE
External links can't include certain URL characters

### ISSUE THREAD

**Issue by socks-the-fox** [socks-the-fox/ComicWings#5]
Because php's parse_ini_file doesn't support quoted keys, we can't include certain characters that are needed for some URLs (the way I found this out was trying to link to a Weasyl profile, which has a `~` in the path). The layout of the file will have to be greatly reworked to better support external links.

**Comment by socks-the-fox** [comment]
`%`-encoding certain characters works for some URLs, but won't work for URLs with GET-encoded parameters

**Comment by WolfWings** [comment]
It's not a bug, it's that you're trying to use unquoted strings.

The following works just fine:

    hiccup="blah.com:8080/~whatever/grep?foo=bar&garbage"
    cough='blah.com:8080/~whatever/grep?foo=bar&garbage'

**Comment by socks-the-fox** [comment]
Yeah, I just gotta figure out how to tie that to the link text as well in a user friendly way. I don't want to have external links split into two sections if I don't have to, but right now it's looking that way...

**Comment by WolfWings** [comment]
Well i guess I'm not understanding the goal here, what external links are ending up in this?

I.E. Show me what you're trying to do? Since I'd think left-side is the title of the nav link, right-side is the URL? parse_ini_file *IS* case sensitive:

    lowercase=Foo
    Lowercase=Bar

...that results in two keys in the returned array. :)

And to me this is nicely readable:

    [leftnav]
    Cast="static/cast"
    Cast/Hero="static/cast#hero"
    Cast/Villain="static/cast#villain"
    
    [rightnav]
    FurAffinity="http://furaffinity.net/user/example"
    Weasyl="http://weasyl.com/~example"

...the only other solution that's readable would be a separate INI file for each nav bar.

**Comment by socks-the-fox** [comment]
Would that support the markdown needed for image links or spaces in titles?

I also don't want to use location-based section names, due to that being a stylistic choice rather than a semantic one. What if someone wanted the external links on the left? Or internal links along the top? That's why I went with `[static]`, `[hidden]` and `[external]`, and am considering changing the 'default' templates and CSS.

**Comment by socks-the-fox** [comment]
Also, the way I currently have it set up is that the key is the URL, and the value is the link text. This is just an extension of how I did the static pages, where the key is the file that gets dumped straight into the regex and the value is the link text.

**Comment by WolfWings** [comment]
You're mixing up what is semantic and what is not, IMO. Semantic isn't based on purpose, it's descriptive of intent.

I also thought we were discussing migrating the nav-bars to an INI file so they can be edited without adding cruft around them, but good point on the images.

So, again, what are you trying to do here? I'm utterly confused by what you're describing now, what's static, what's hidden, what's external? Huh? What? Where are these tied together?

**Comment by socks-the-fox** [comment]
In the current `static/metadata.ini` there are 3 sections related to defining pages and links:

* `[static]` contains internal pages (such as the cast page) that *will* show up on the menu by default
* `[hidden]` contains internal pages that will *not* show up on the menu by default but that the user may still want defined and accessible (the static frontpage module currently in use on Fox's site uses this, and individual character bio pages might use this and be accessed via links from the main cast page)
* `[external]` contains links to other sites, such as a patreon page or external art galleries, that will show up in the other menu.

You can check the one that's in the repo to see examples of how it's currently being done. As of right now, they all use the same general `link = "Markdown-formatted Title"` format. The issue is that the `link` part doesn't cover all common use cases for external links.

My reason for not wanting to call them `[leftnav]` and `[rightnav]` is that on some people's designs, they may not be on the left or right. That is a separate issue, though.

**Comment by socks-the-fox** [comment]
I've figured one potential solution to this: Use a JSON file instead of an INI file. It's a tad more verbose and the PHP parser doesn't allow comments without pre-processing it though.

**Comment by socks-the-fox** [comment]
Actually it would allow a more logical presentation as well, instead of the current hacky `url-as-key = "Markdown formatted title"` setup it could be an array of `{"link": "url", "title": "Markdown formatted title}` objects...
